language: php
dist: trusty

services:
  - mysql

php:
  - 5.6
  - 7.1

before_install:
  - mysql -e 'CREATE DATABASE sufel_dev DEFAULT CHARACTER SET utf8;'

before_script:
  - mysql -u root sufel_dev < data/schema/schema.sql
#  - php bin/db/init-db.php
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev
  - composer require php-coveralls/php-coveralls

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
